add reverse ping-pong
Nerixyz/mqtts pull request #29
Opened 2021-05-21 22:53 UTC by f0rr0

Related https://github.com/Nerixyz/mqtts/issues/28

2021-05-22 11:22 UTC, Nerixyz requested changes

2021-05-22 11:22 UTC, Nerixyz commented on src/mqtt.client.ts
> +            .then(() => this.pingDebug(`PingPong @ ${Date.now()}`))
This should say something different. Something like `Server-PingPong` as it's not the traditional pingpong.

2021-05-22 11:22 UTC, Nerixyz commented on src/flow/incoming.flows.ts
> +export function incomingPingFlow(): PacketFlowFunc<DefaultPacketReadResultMap, DefaultPacketWriteOptions ,void> {
Could you please format the code.

2021-05-22 18:08 UTC, f0rr0 commented on src/flow/incoming.flows.ts
> +export function incomingPingFlow(): PacketFlowFunc<DefaultPacketReadResultMap, DefaultPacketWriteOptions ,void> {
resolved

2021-05-24 08:30 UTC, Nerixyz approved these changes

2021-05-24 08:31 UTC, merged